version: '3.4'

services:
  profile.webapi:
    image: profilewebapi:dev
    container_name: Profile.WebAPI
    build:
      target: base
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "Profile.WebAPI"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=true
      #- NUGET_FALLBACK_PACKAGES=$container_paths_to_fallback_packages_profile.webapi$
    volumes:
      - F:\Repos\2020-2021\Mahindra\2511_DigisenseMicroServices\Profile.WebAPI:/app
      - F:\Repos\2020-2021\Mahindra\2511_DigisenseMicroServices:/src
      - C:\Users\udhayakumar\vsdbg\vs2017u5:/remote_debugger:rw
#$nuget_volume_mapping_profile.webapi$
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      #com.microsoft.visualstudio.debuggee.arguments: " $debuggee_arguments_probing_paths_profile.webapi$ \"/app/bin/Debug/netcoreapp3.1/Profile.WebAPI.dll\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/sh -c \"if PID=$$(pidof dotnet); then kill $$PID; fi\""
    tty: true
  unifiedlogin.webapi:
    image: unifiedloginwebapi:dev
    container_name: UnifiedLogin.WebAPI
    build:
      target: base
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "UnifiedLogin.WebAPI"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=true
      #- NUGET_FALLBACK_PACKAGES=$container_paths_to_fallback_packages_unifiedlogin.webapi$
    volumes:
      - F:\Repos\2020-2021\Mahindra\2511_DigisenseMicroServices\UnifiedLogin.WebAPI:/app
      - F:\Repos\2020-2021\Mahindra\2511_DigisenseMicroServices:/src
      - C:\Users\udhayakumar\vsdbg\vs2017u5:/remote_debugger:rw
#$nuget_volume_mapping_unifiedlogin.webapi$
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      #com.microsoft.visualstudio.debuggee.arguments: " $debuggee_arguments_probing_paths_unifiedlogin.webapi$ \"/app/bin/Debug/netcoreapp3.1/UnifiedLogin.WebAPI.dll\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/sh -c \"if PID=$$(pidof dotnet); then kill $$PID; fi\""
    tty: true
